name: Run on New Files Added to Doc Folder

on:
  push:
    paths:
      - 'doc/**'

jobs:
  check-new-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify about new files
        run: echo "file added"
